[versions]
agp = "8.9.2"
kotlin = "2.1.10"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version = "1.15.0" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version = "1.7.0" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version = "2.2.1" }

google-material = { group = "com.google.android.material", name = "material", version = "1.12.0" }


junit = { group = "junit", name = "junit", version = "4.13.2" }
androidx-test-junit = { group = "androidx.test.ext", name = "junit", version = "1.2.1" }
androidx-test-espresso = { group = "androidx.test.espresso", name = "espresso-core", version = "3.6.1" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }

